%dev.quarkus.http.port=8081
quarkus.http.access-log.enabled=true

keycloak.admin.instance=${KEYCLOAK_INSTANCE:http://localhost:8080/}
keycloak.admin.user=${KEYCLOAK_ADMIN_USER:sub3}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD}
keycloak.admin.auth-realm=${KEYCLOAK_ADMIN_AUTH_REALM:master}
keycloak.admin.realm=${KEYCLOAK_ADMIN_REALM:sub3}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}

quarkus.datasource.devservices.enabled=false
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER:sub3}
quarkus.datasource.password=${POSTGRES_PASSWORD:sub3}
quarkus.datasource.jdbc.url=${POSTGRES_URL:jdbc:postgresql://postgres:5432/compradores}

%dev.keycloak.admin.instance=${DEV_KEYCLOAK_INSTANCE:http://localhost:8080/}
%dev.keycloak.admin.user=${DEV_KEYCLOAK_ADMIN_USER:sub3}
%dev.keycloak.admin.password=${DEV_KEYCLOAK_ADMIN_PASSWORD}
%dev.keycloak.admin.auth-realm=${DEV_KEYCLOAK_ADMIN_AUTH_REALM:master}
%dev.keycloak.admin.realm=${DEV_KEYCLOAK_ADMIN_REALM:sub3}
%dev.keycloak.admin.client-id=${DEV_KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}

%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=${DEV_POSTGRES_USER:sub3}
%dev.quarkus.datasource.password=${DEV_POSTGRES_PASSWORD:sub3}
%dev.quarkus.datasource.jdbc.url=${DEV_POSTGRES_URL:jdbc:postgresql://localhost:5432/compradores}
