%dev.quarkus.http.port=8081
quarkus.http.access-log.enabled=true

cognito.region=${AWS_REGION:sa-east-1}
cognito.user-pool-id=${COGNITO_USER_POOL_ID:}
cognito.aws-profile=${COGNITO_AWS_PROFILE:}
cognito.comprador-group=${COGNITO_COMPRADOR_GROUP:comprador}

quarkus.datasource.devservices.enabled=false
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER:sub3}
quarkus.datasource.password=${POSTGRES_PASSWORD:sub3}
quarkus.datasource.jdbc.url=${POSTGRES_URL:jdbc:postgresql://postgres:5432/compradores}

%dev.cognito.region=${DEV_AWS_REGION:${AWS_REGION:sa-east-1}}
%dev.cognito.user-pool-id=${DEV_COGNITO_USER_POOL_ID:${COGNITO_USER_POOL_ID:}}
%dev.cognito.aws-profile=${DEV_COGNITO_AWS_PROFILE:${COGNITO_AWS_PROFILE:}}
%dev.cognito.comprador-group=${DEV_COGNITO_COMPRADOR_GROUP:${COGNITO_COMPRADOR_GROUP:comprador}}

%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=${DEV_POSTGRES_USER:sub3}
%dev.quarkus.datasource.password=${DEV_POSTGRES_PASSWORD:sub3}
%dev.quarkus.datasource.jdbc.url=${DEV_POSTGRES_URL:jdbc:postgresql://localhost:5432/compradores}
