apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoicmNjcnYiLCJwYXNzd29yZCI6ImdocF9qUHBRM2JIbEdNZGdqVVZOV1h1dWVVMHdTUjMzU1gwU3UzV2YiLCJlbWFpbCI6InJhdC5jYXJ2YWxob0BnbWFpbC5jb20iLCJhdXRoIjoiY21OamNuWTZaMmh3WDJwUWNGRXpZa2hzUjAxa1oycFZWazVYV0hWMVpWVXdkMU5TTXpOVFdEQlRkVE5YWmc9PSJ9fX0=
kind: Secret
metadata:
  name: ghcr-secret
  namespace: pos-tech
type: kubernetes.io/dockerconfigjson