%dev.quarkus.http.port=8084

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER:sub3}
quarkus.datasource.password=${POSTGRES_PASSWORD:sub3}
quarkus.datasource.jdbc.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/financeiro}

financeiro.payment.timeout=PT15M
%test.financeiro.payment.timeout=PT30S
financeiro.payment.expiry-scan=30s

quarkus.kafka.devservices.enabled=false
kafka.bootstrap.servers=${KAFKA_SERVER:localhost:9092}

mp.messaging.outgoing.orquestrador-out.connector=smallrye-kafka
mp.messaging.outgoing.orquestrador-out.topic=financeiro-ack

mp.messaging.incoming.orquestrador-in.connector=smallrye-kafka
mp.messaging.incoming.orquestrador-in.topic=financeiro
